export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};

export const PROCESS_STATUS = {
  INITIALIZED: 'initialized',
  PARSING_CURL: 'parsing_curl', 
  GENERATING_TEST_CASES: 'generating_test_cases',
  EXECUTING_TEST_CASES: 'executing_test_cases',
  COMPLETED: 'completed',
  ERROR: 'error'
};

export const DEFAULT_CONFIG = {
  MAX_RETRIES: 3,
  MAX_FIELD_LENGTH: 128,
  REQUEST_TIMEOUT: 15000,
  AI_TEMPERATURE: 0.3,
  MAX_OUTPUT_TOKENS: 8192,
  MAX_CURL_LENGTH: 50000,
  MAX_TEST_CASES: 50
};

export const COLLECTIONS = {
  CURL_PROCESSES: 'curl_processes',
  TEST_CASES: 'test_cases', 
  AI_INTERACTIONS: 'ai_interactions'
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  AI_PROCESSING_ERROR: 'AI_PROCESSING_ERROR',
  CURL_PARSING_ERROR: 'CURL_PARSING_ERROR',
  TEST_EXECUTION_ERROR: 'TEST_EXECUTION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR'
};

export const LOG_LEVELS = {
  ERROR: 0,
  WARN: 1,
  INFO: 2,
  DEBUG: 3
};
