apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urtest-keyword-extractor
  namespace: urtest
  labels:
    app: urtest-keyword-extractor
spec:
  serviceName: urtest-keyword-extractor
  replicas: 1
  selector:
    matchLabels:
      app: urtest-keyword-extractor
  template:
    metadata:
      labels:
        app: urtest-keyword-extractor
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'urtest-keyword-extractor-dev'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-env-config: 'kv/urtest-keyword-extractor-dev'
        vault.hashicorp.com/agent-inject-template-env-config: |
            {{ with secret "kv/urtest-keyword-extractor-dev" -}}
              {{- range $key, $value := .Data.data }}
                export {{ $key }}="{{ $value }}"
              {{- end }}
            {{- end }}
    spec:
      serviceAccountName: urtest-keyword-extractor-dev-auth
      containers:
        - name: urtest-keyword-extractor
          image: ideavn/urtest-keyword-extractor:{latest}
          ports:
            - containerPort: 3022
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: urtest-keyword-extractor-service
  namespace: urtest
spec:
  selector:
    app: urtest-keyword-extractor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3022
      targetPort: 3022
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urtest-keyword-extractor-ingress
  namespace: urtest
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: keyword-extractor.urtest.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urtest-keyword-extractor-service
            port:
              number: 3022
