apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urtest-frontend
  namespace: urtest
  labels:
    app: urtest-frontend
spec:
  serviceName: urtest-frontend
  replicas: 4
  selector:
    matchLabels:
      app: urtest-frontend
  template:
    metadata:
      labels:
        app: urtest-frontend
    spec:
      containers:
        - name: urtest-frontend
          image: ideavn/urtest-frontend:{latest}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 64m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: urtest-frontend-service
  namespace: urtest
spec:
  selector:
    app: urtest-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urtest-frontend-ingress
  namespace: urtest
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: urtest.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urtest-frontend-service
            port:
              number: 3000
