apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urtest-backend
  namespace: urtest
  labels:
    app: urtest-backend
spec:
  serviceName: urtest-backend
  replicas: 2
  selector:
    matchLabels:
      app: urtest-backend
  template:
    metadata:
      labels:
        app: urtest-backend
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'urtest-backend-dev'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-env-config: 'kv/urtest-backend-dev'
        vault.hashicorp.com/agent-inject-template-env-config: |
            {{ with secret "kv/urtest-backend-dev" -}}
              {{- range $key, $value := .Data.data }}
                export {{ $key }}="{{ $value }}"
              {{- end }}
            {{- end }}
    spec:
      serviceAccountName: urtest-backend-dev-auth
      containers:
        - name: urtest-backend
          image: ideavn/urtest-backend:{latest}
          ports:
            - containerPort: 3020
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 64m
              memory: 64m
---
apiVersion: v1
kind: Service
metadata:
  name: urtest-backend-service
  namespace: urtest
spec:
  selector:
    app: urtest-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urtest-backend-ingress
  namespace: urtest
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: api.urtest.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urtest-backend-service
            port:
              number: 3020
