name: Deploy Keyword Extractor Service

on:
  push:
    branches:
      - deploy-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          docker buildx create --name builder --use
          docker buildx inspect builder --bootstrap
          docker buildx build -t ideavn/urtest-backend:${{ github.run_number }} --push ./backend/.

  deploy:
    needs: build
    if: ${{ success() && needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          version: "latest"

      - name: Apply Kubernetes deployment
        run: |
          kubectl apply -f ./backend/deployment/namespace.yaml
          kubectl apply -f ./backend/deployment/service-account.yaml
          sed -i 's/{latest}/${{ github.run_number }}/g' ./backend/deployment/main.yaml
          kubectl apply -f ./backend/deployment/main.yaml --validate=false
